import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="h-full bg-[#E5E5E5]">
        <span className="absolute w-full h-1/2 -z-10 top-0 left-0 bg-[#6B46C1]"></span>
        {children}
      </body>
    </html>
  );
}
